### ISSUE TITLE
Packal Link doesn't work anymore

### ISSUE THREAD

**Issue by Qhilm** [schwark/alfred-simplelogin#1]
The packal link from the Readme does not work anymore:

http://www.packal.org/workflow/simplelogin-workflow

**Comment by joedemcher** [comment]
+1
Is this going to be updated?

**Comment by schwark** [comment]
Unfortunately, I don't think Packal is maintained anymore - I have not been able to add a new workflow there.. However, the workflow can be installed from the releases page on this GitHub project.. And it will update itself automatically from GitHub as well.
