### ISSUE TITLE
Create a new contact for an alias 

### ISSUE THREAD

**Issue by joedemcher** [schwark/alfred-simplelogin#4]
Hello! 👋🏻 

Is there a way to create a new contact for an alias? Or am I just missing it?

I didn't see it in your README but I see there is an option when I enter the alias address that says "Contact" followed by the alias address but when I select it I get a notification that says the entered alias was contacted and that's it. I also tried adding `contact` followed by the email address I am looking to add as a contact for that alias but that didn't seem to do anything except deliver the same notification. I checked the mobile app to confirm the contact was not added.

What does `contact` do? It's not even listed as an option in the [alias commands](https://github.com/schwark/alfred-simplelogin?tab=readme-ov-file#alias-commands) portion of the README.

If this capability is not yet implemented would you be open to adding it to the workflow? I know the [SimpleLogin API has that available](https://github.com/simple-login/app/blob/master/docs/api.md#post-apialiasesalias_idcontacts) and I think it would be a great and useful addition.

If you're open to it I could take a swing at it, I'm familiar with Python and your codebase is well laid out so that part isn't too difficult. I would just have to read up on how it interacts with Alfred as I've never built a workflow myself that runs a Python script.

Let me know what you think and if you want to move forward with this.

Also, thank you for creating this, because I was in the process of exploring building a workflow for SimpleLogin after I found out there wasn't one but I just never had the time. :pink_heart:

**Comment by schwark** [comment]
I had in fact written this entire workflow to enable that exact use case, but the update of the data takes so freaking long as the contacts don’t have a bulk API and you have to make hundreds of API calls to get all the contacts, so I ended up not implementing the create contact.. I can do that.. It will be a few weeks before I can get to it though..

Best,

ss

**Comment by joedemcher** [comment]
Great, thank you! I look forward to that update whenever it comes. 👍🏻

**Comment by schwark** [comment]
Now available in v0.0.6
